/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author joaop
 */
public class bolderlayout extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public bolderlayout() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfPrimeiroValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfSegundoValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfResultado = new javax.swing.JTextField();
        jbCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Digite o primeiro numero");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);

        jtfPrimeiroValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrimeiroValorActionPerformed(evt);
            }
        });
        getContentPane().add(jtfPrimeiroValor);

        jLabel2.setText("Digite o segundo numero");
        getContentPane().add(jLabel2);
        getContentPane().add(jtfSegundoValor);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resultado");
        getContentPane().add(jLabel3);

        jtfResultado.setEditable(false);
        jtfResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(jtfResultado);

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jbCalcular);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPrimeiroValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrimeiroValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrimeiroValorActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        // TODO add your handling code here:
        Integer primeiroValor = Integer.valueOf(jtfPrimeiroValor.getText());
        Integer segundoValor = Integer.valueOf(jtfSegundoValor.getText());
        
        Integer resultado = primeiroValor+segundoValor;
        jtfResultado.setText(resultado.toString());
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jtfResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bolderlayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bolderlayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bolderlayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bolderlayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bolderlayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JTextField jtfPrimeiroValor;
    private javax.swing.JTextField jtfResultado;
    private javax.swing.JTextField jtfSegundoValor;
    // End of variables declaration//GEN-END:variables
}
